### ISSUE TITLE
Configure LoRA URLs as an array instead of single line separated by |

### ISSUE THREAD

**Issue by basicfeatures** [dreamingtulpa/replicate-ruby#4]
Could we express it this way instead?

```
lora_urls: {
  "https://huggingface.co/SG161222/Realistic_Vision_V2.0/blob/main/Realistic_Vision_V2.0-fp16-no-ema-inpainting.safetensors",
  "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors"
}
```
of a pipe-searated single line?

Thanks!

**Comment by dreamingtulpa** [comment]
As the `|` syntax for `lora_urls` is unique to the https://replicate.com/cloneofsimo/lora model and I don't know of any other model where this is the case, I would suggest doing this on your side at the moment as this is pretty easy to solve:

```
  lora_urls: your_lora_urls_array.join("|")
```
